version: "3.9"

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Node API service
  api:
    container_name: node_container
    build: .
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_DB_LOCAL_URI: mongodb://mongo_db:27017
      DB_NAME: newsRestApi
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
